apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-entity-api-deployment
  labels:
    app: add-entity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-entity-api
  template:
    metadata:
      labels:
        app: add-entity-api
    spec:
      containers:
      - name: add-entity-api
        image: jiocontainerregistry.azurecr.io/knowledge_graph/add_entity_api:v1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 31002
---
apiVersion: v1
kind: Service
metadata:
  name: add-entity-service
spec:
  selector:
    app: add-entity-api
  ports:
    - name: tcp-port
      targetPort: 31002
      port: 31002
      protocol: TCP
  type: ClusterIP