apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-canonical-name-api-deployment
  labels:
    app: delete-canonical-name-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete-canonical-name-api
  template:
    metadata:
      labels:
        app: delete-canonical-name-api
    spec:
      containers:
      - name: delete-canonical-name-api
        image: jiocontainerregistry.azurecr.io/knowledge_graph/delete_canonical_name_api:v1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 31027
---
apiVersion: v1
kind: Service
metadata:
  name: delete-canonical-name-service
spec:
  selector:
    app: delete-canonical-name-api
  ports:
    - name: tcp-port
      targetPort: 31027
      port: 31027
      protocol: TCP
  type: ClusterIP