apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-entity-alias-api-deployment
  labels:
    app: delete-entity-alias-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete-entity-alias-api
  template:
    metadata:
      labels:
        app: delete-entity-alias-api
    spec:
      containers:
      - name: delete-entity-alias-api
        image: jiocontainerregistry.azurecr.io/knowledge_graph/delete_entity_alias_api:v1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 31031
---
apiVersion: v1
kind: Service
metadata:
  name: delete-entity-alias-service
spec:
  selector:
    app: delete-entity-alias-api
  ports:
    - name: tcp-port
      targetPort: 31031
      port: 31031
      protocol: TCP
  type: ClusterIP