apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-schema-api-deployment
  labels:
    app: get-schema-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-schema-api
  template:
    metadata:
      labels:
        app: get-schema-api
    spec:
      containers:
      - name: get-schema-api
        image: jiocontainerregistry.azurecr.io/knowledge_graph/get_schema_api:v1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 31036
---
apiVersion: v1
kind: Service
metadata:
  name: get-schema-service
spec:
  selector:
    app: get-schema-api
  ports:
    - name: tcp-port
      targetPort: 31036
      port: 31036
      protocol: TCP
  type: ClusterIP
