apiVersion: apps/v1
kind: Deployment
metadata:
  name: has-biz-id-api-deployment
  labels:
    app: has-biz-id-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: has-biz-id-api
  template:
    metadata:
      labels:
        app: has-biz-id-api
    spec:
      containers:
      - name: has-biz-id-api
        image: jiocontainerregistry.azurecr.io/knowledge_graph/has_biz_id_api:v1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 31012
---
apiVersion: v1
kind: Service
metadata:
  name: has-biz-id-service
spec:
  selector:
    app: has-biz-id-api
  ports:
    - name: tcp-port
      targetPort: 31012
      port: 31012
      protocol: TCP
  type: ClusterIP