apiVersion: apps/v1
kind: Deployment
metadata:
  name: has-any-biz-id-api-deployment
  labels:
    app: has-any-biz-id-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: has-any-biz-id-api
  template:
    metadata:
      labels:
        app: has-any-biz-id-api
    spec:
      containers:
      - name: has-any-biz-id-api
        image: jiocontainerregistry.azurecr.io/knowledge_graph/has_any_biz_id_api:v1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 31033
---
apiVersion: v1
kind: Service
metadata:
  name: has-any-biz-id-service
spec:
  selector:
    app: has-any-biz-id-api
  ports:
    - name: tcp-port
      targetPort: 31033
      port: 31033
      protocol: TCP
  type: ClusterIP