apiVersion: apps/v1
kind: Deployment
metadata:
  name: has-canonical-name-api-deployment
  labels:
    app: has-canonical-name-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: has-canonical-name-api
  template:
    metadata:
      labels:
        app: has-canonical-name-api
    spec:
      containers:
      - name: has-canonical-name-api
        image: jiocontainerregistry.azurecr.io/knowledge_graph/has_canonical_name_api:v1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 31020
---
apiVersion: v1
kind: Service
metadata:
  name: has-canonical-name-service
spec:
  selector:
    app: has-canonical-name-api
  ports:
    - name: tcp-port
      targetPort: 31020
      port: 31020
      protocol: TCP
  type: ClusterIP