apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-lookup-api-v2-deployment
  labels:
    app: metadata-lookup-api-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-lookup-api-v2
  template:
    metadata:
      labels:
        app: metadata-lookup-api-v2
    spec:
      containers:
      - name: metadata-lookup-api-v2
        image: jiocontainerregistry.azurecr.io/knowledge_graph/metadata_lookup_api:v2.1
        imagePullPolicy: Always
        ports:
          - containerPort: 31056
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-lookup-service-v2
spec:
  selector:
    app: metadata-lookup-api-v2
  ports:
    - name: tcp-port
      targetPort: 31056
      port: 31056
      protocol: TCP
  type: ClusterIP
