apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-bizid-to-entity-api-deployment
  labels:
    app: update-bizid-to-entity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: update-bizid-to-entity-api
  template:
    metadata:
      labels:
        app: update-bizid-to-entity-api
    spec:
      containers:
      - name: update-bizid-to-entity-api
        image: jiocontainerregistry.azurecr.io/knowledge_graph/update_bizid_to_entity_api:v1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 31034
---
apiVersion: v1
kind: Service
metadata:
  name: update-bizid-to-entity-service
spec:
  selector:
    app: update-bizid-to-entity-api
  ports:
    - name: tcp-port
      targetPort: 31034
      port: 31034
      protocol: TCP
  type: ClusterIP