apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-knowledge-api-deployment
  labels:
    app: healthcare-knowledge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-knowledge-api
  template:
    metadata:
      labels:
        app: healthcare-knowledge-api
    spec:
      containers:
      - name: healthcare-knowledge-api
        image: jiocontainerregistry.azurecr.io/knowledge_graph/healthcare_knowledge_apis:0.2
        imagePullPolicy: Always
        ports:
          - containerPort: 31050
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-knowledge-service
spec:
  selector:
    app: healthcare-knowledge-api
  ports:
    - name: tcp-port
      targetPort: 31050
      port: 31050
      protocol: TCP
  type: ClusterIP

