server_healthcare_knowledge_api:
	python -m healthkg.server

client_get_all_disease:
	python -m healthkg.test.get_all_disease.test

client_get_all_symptom:
	python -m healthkg.test.get_all_symptom.test

client_get_disease_by_id:
	python -m healthkg.test.get_disease_by_id.test

client_get_disease:
	python -m healthkg.test.get_disease.test

client_get_disease_id:
	python -m healthkg.test.get_disease_id.test

client_get_disease_patient_state:
	python -m healthkg.test.get_disease_patient_state.test

client_get_symptom_id:
	python -m healthkg.test.get_symptom_id.test

client_get_symptom_patient_state:
	python -m healthkg.test.get_symptom_patient_state.test

client_get_symptom_by_id:
	python -m healthkg.test.get_symptom_by_id.test

client_get_symptom:
	python -m healthkg.test.get_symptom.test

client_get_attribute:
	python -m healthkg.test.get_attribute.test

client_get_attribute_id:
	python -m healthkg.test.get_attribute_id.test

client_get_attribute_value_id:
	python -m healthkg.test.get_attribute_value_id.test

client_get_attribute_name:
	python -m healthkg.test.get_attribute_name.test

client_get_attribute_value:
	python -m healthkg.test.get_attribute_value.test

client_get_context:
	python -m healthkg.test.get_context.test

client_get_context_id:
	python -m healthkg.test.get_context_id.test

client_get_context_by_id:
	python -m healthkg.test.get_context_by_id.test

client_get_context_value_id:
	python -m healthkg.test.get_context_value_id.test

client_get_disease_given_symptom:
	python -m healthkg.test.get_disease_given_symptom.test

client_get_symptom_given_disease:
	python -m healthkg.test.get_symptom_given_disease.test

client_get_attribute_order:
	python -m healthkg.test.get_attribute_order.test

client_get_symptom_bucket_in_disease:
	python -m healthkg.test.get_symptom_bucket_in_disease.test

client_get_highest_attribute_bucket:
	python -m healthkg.test.get_highest_attribute_bucket.test

client_get_attribute_bucket_in_disease:
	python -m healthkg.test.get_attribute_bucket_in_disease.test

client_get_attributes_of_symptom_and_disease:
	python -m healthkg.test.get_attributes_of_symptom_and_disease.test

client_search_symptoms:
	python -m healthkg.test.search_symptoms.test

client_search_diseases:
	python -m healthkg.test.search_diseases.test

client_get_valid_symptom_attribute_values_given_filter:
	python -m healthkg.test.get_valid_symptom_attribute_values_given_filter.test
	
client_get_context_name:
	python -m healthkg.test.get_context_name.test

client_get_disease_name:
	python -m healthkg.test.get_disease_name.test

client_get_symptom_name:
	python -m healthkg.test.get_symptom_name.test

client_get_attribute_value_name:
	python -m healthkg.test.get_attribute_value_name.test

client_get_context_value_name:
	python -m healthkg.test.get_context_value_name.test