trigger:
  tags:
    include:
      - '*'
#  branches:
#    include:
#      - develop
#      - master
#variables:
# https_proxy: http://prodproxy.jio.com:8080
# http_proxy: http://prodproxy.jio.com:8080
  
stages:
- stage: Nexus_release
  variables:
    venv_dir: ./protoutilsenv
    nexus_host: nexus.rjil.ril.com
    repository_url: http://10.141.51.157:9081/repository/Brain_os-py/
    index_url: http://Brain_os:Brain_os@nexus.rjil.ril.com:9081/repository/Brain_os-py-group/simple/

  jobs:
  - job: create_virtualenv
    pool:
      name: 'JioBuildAgent'
    steps:
    - script: |
        pip3 install virtualenv --trusted-host $(nexus_host) --index-url $(index_url)
        python3 -m venv ./protoutilsenv
        source $(venv_dir)/bin/activate
        pip install --upgrade pip --trusted-host $(nexus_host) --index-url $(index_url)
        pip install twine --trusted-host $(nexus_host) --index-url $(index_url)
      displayName: Download, install & activate virtualenv
    - bash: |
        git tag --sort=-creatordate
        tag=$(git tag --sort=-creatordate | head -n 1)
        version=$tag
        echo "##vso[task.setvariable variable=version]$(git tag --sort=-creatordate | head -n 1)"
        echo "Version=$(version)"
      displayName: Get tag
    - script: |
        current_version=$(grep "version=\".*\"" setup.py | awk -F'"' '{print $2}')
        new_version=$(git tag --sort=-creatordate | head -n 1)
        sed -i 's/version="'${current_version}'"/version="'${new_version}'"/g' setup.py
        cat setup.py
      displayName: Set version in setup.py
    - script: |
        source $(venv_dir)/bin/activate
        python3 setup.py sdist
        twine upload -r nexus --repository-url $(repository_url) -u Brain_os -p Brain_os ./dist/*
      displayName: Build dist and upload
    - script: |
        source $(venv_dir)/bin/activate
        version=$(git tag --sort=-creatordate | head -n 1)
        pip3 install protoutils==$version --trusted-host $(nexus_host) --index-url $(index_url)
        protoutils -h
      displayName: pip install and test with "protoutils -h"
