# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jio/brain/proto/knowledge/healthcare/req_res/get_all_disease.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jio.brain.proto.knowledge.healthcare.base import disease_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_disease__pb2
from jio.brain.proto.knowledge.healthcare.base import status_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jio/brain/proto/knowledge/healthcare/req_res/get_all_disease.proto',
  package='jio.brain.proto.knowledge.healthcare',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nBjio/brain/proto/knowledge/healthcare/req_res/get_all_disease.proto\x12$jio.brain.proto.knowledge.healthcare\x1a\x37jio/brain/proto/knowledge/healthcare/base/disease.proto\x1a\x36jio/brain/proto/knowledge/healthcare/base/status.proto\"\x16\n\x14GetAllDiseaseRequest\"\x9f\x01\n\x15GetAllDiseaseResponse\x12\x43\n\x07\x64isease\x18\x01 \x03(\x0b\x32\x32.jio.brain.proto.knowledge.healthcare.base.Disease\x12\x41\n\x06status\x18\x02 \x01(\x0b\x32\x31.jio.brain.proto.knowledge.healthcare.base.Statusb\x06proto3'
  ,
  dependencies=[jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_disease__pb2.DESCRIPTOR,jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2.DESCRIPTOR,])




_GETALLDISEASEREQUEST = _descriptor.Descriptor(
  name='GetAllDiseaseRequest',
  full_name='jio.brain.proto.knowledge.healthcare.GetAllDiseaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=243,
)


_GETALLDISEASERESPONSE = _descriptor.Descriptor(
  name='GetAllDiseaseResponse',
  full_name='jio.brain.proto.knowledge.healthcare.GetAllDiseaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='disease', full_name='jio.brain.proto.knowledge.healthcare.GetAllDiseaseResponse.disease', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='jio.brain.proto.knowledge.healthcare.GetAllDiseaseResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=405,
)

_GETALLDISEASERESPONSE.fields_by_name['disease'].message_type = jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_disease__pb2._DISEASE
_GETALLDISEASERESPONSE.fields_by_name['status'].message_type = jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2._STATUS
DESCRIPTOR.message_types_by_name['GetAllDiseaseRequest'] = _GETALLDISEASEREQUEST
DESCRIPTOR.message_types_by_name['GetAllDiseaseResponse'] = _GETALLDISEASERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetAllDiseaseRequest = _reflection.GeneratedProtocolMessageType('GetAllDiseaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLDISEASEREQUEST,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.get_all_disease_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.GetAllDiseaseRequest)
  })
_sym_db.RegisterMessage(GetAllDiseaseRequest)

GetAllDiseaseResponse = _reflection.GeneratedProtocolMessageType('GetAllDiseaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETALLDISEASERESPONSE,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.get_all_disease_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.GetAllDiseaseResponse)
  })
_sym_db.RegisterMessage(GetAllDiseaseResponse)


# @@protoc_insertion_point(module_scope)
