# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jio/brain/proto/knowledge/healthcare/req_res/get_attribute_bucket_in_disease.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jio.brain.proto.knowledge.healthcare.base import status_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jio/brain/proto/knowledge/healthcare/req_res/get_attribute_bucket_in_disease.proto',
  package='jio.brain.proto.knowledge.healthcare',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nRjio/brain/proto/knowledge/healthcare/req_res/get_attribute_bucket_in_disease.proto\x12$jio.brain.proto.knowledge.healthcare\x1a\x36jio/brain/proto/knowledge/healthcare/base/status.proto\"b\n\"GetAttributeBucketInDiseaseRequest\x12\x12\n\ndisease_id\x18\x01 \x01(\r\x12\x12\n\nsymptom_id\x18\x02 \x01(\r\x12\x14\n\x0c\x61ttribute_id\x18\x03 \x01(\r\"x\n#GetAttributeBucketInDiseaseResponse\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\r\x12\x41\n\x06status\x18\x02 \x01(\x0b\x32\x31.jio.brain.proto.knowledge.healthcare.base.Statusb\x06proto3'
  ,
  dependencies=[jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2.DESCRIPTOR,])




_GETATTRIBUTEBUCKETINDISEASEREQUEST = _descriptor.Descriptor(
  name='GetAttributeBucketInDiseaseRequest',
  full_name='jio.brain.proto.knowledge.healthcare.GetAttributeBucketInDiseaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='disease_id', full_name='jio.brain.proto.knowledge.healthcare.GetAttributeBucketInDiseaseRequest.disease_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symptom_id', full_name='jio.brain.proto.knowledge.healthcare.GetAttributeBucketInDiseaseRequest.symptom_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attribute_id', full_name='jio.brain.proto.knowledge.healthcare.GetAttributeBucketInDiseaseRequest.attribute_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=278,
)


_GETATTRIBUTEBUCKETINDISEASERESPONSE = _descriptor.Descriptor(
  name='GetAttributeBucketInDiseaseResponse',
  full_name='jio.brain.proto.knowledge.healthcare.GetAttributeBucketInDiseaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bucket', full_name='jio.brain.proto.knowledge.healthcare.GetAttributeBucketInDiseaseResponse.bucket', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='jio.brain.proto.knowledge.healthcare.GetAttributeBucketInDiseaseResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=400,
)

_GETATTRIBUTEBUCKETINDISEASERESPONSE.fields_by_name['status'].message_type = jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2._STATUS
DESCRIPTOR.message_types_by_name['GetAttributeBucketInDiseaseRequest'] = _GETATTRIBUTEBUCKETINDISEASEREQUEST
DESCRIPTOR.message_types_by_name['GetAttributeBucketInDiseaseResponse'] = _GETATTRIBUTEBUCKETINDISEASERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetAttributeBucketInDiseaseRequest = _reflection.GeneratedProtocolMessageType('GetAttributeBucketInDiseaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETATTRIBUTEBUCKETINDISEASEREQUEST,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.get_attribute_bucket_in_disease_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.GetAttributeBucketInDiseaseRequest)
  })
_sym_db.RegisterMessage(GetAttributeBucketInDiseaseRequest)

GetAttributeBucketInDiseaseResponse = _reflection.GeneratedProtocolMessageType('GetAttributeBucketInDiseaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETATTRIBUTEBUCKETINDISEASERESPONSE,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.get_attribute_bucket_in_disease_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.GetAttributeBucketInDiseaseResponse)
  })
_sym_db.RegisterMessage(GetAttributeBucketInDiseaseResponse)


# @@protoc_insertion_point(module_scope)
