# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jio/brain/proto/knowledge/healthcare/req_res/get_context_name.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jio.brain.proto.knowledge.healthcare.base import context_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_context__pb2
from jio.brain.proto.knowledge.healthcare.base import status_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jio/brain/proto/knowledge/healthcare/req_res/get_context_name.proto',
  package='jio.brain.proto.knowledge.healthcare',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nCjio/brain/proto/knowledge/healthcare/req_res/get_context_name.proto\x12$jio.brain.proto.knowledge.healthcare\x1a\x37jio/brain/proto/knowledge/healthcare/base/context.proto\x1a\x36jio/brain/proto/knowledge/healthcare/base/status.proto\"+\n\x15GetContextNameRequest\x12\x12\n\ncontext_id\x18\x01 \x01(\r\"q\n\x16GetContextNameResponse\x12\x14\n\x0c\x63ontext_name\x18\x01 \x01(\t\x12\x41\n\x06status\x18\x02 \x01(\x0b\x32\x31.jio.brain.proto.knowledge.healthcare.base.Statusb\x06proto3'
  ,
  dependencies=[jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_context__pb2.DESCRIPTOR,jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2.DESCRIPTOR,])




_GETCONTEXTNAMEREQUEST = _descriptor.Descriptor(
  name='GetContextNameRequest',
  full_name='jio.brain.proto.knowledge.healthcare.GetContextNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='context_id', full_name='jio.brain.proto.knowledge.healthcare.GetContextNameRequest.context_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=265,
)


_GETCONTEXTNAMERESPONSE = _descriptor.Descriptor(
  name='GetContextNameResponse',
  full_name='jio.brain.proto.knowledge.healthcare.GetContextNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='context_name', full_name='jio.brain.proto.knowledge.healthcare.GetContextNameResponse.context_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='jio.brain.proto.knowledge.healthcare.GetContextNameResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=380,
)

_GETCONTEXTNAMERESPONSE.fields_by_name['status'].message_type = jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2._STATUS
DESCRIPTOR.message_types_by_name['GetContextNameRequest'] = _GETCONTEXTNAMEREQUEST
DESCRIPTOR.message_types_by_name['GetContextNameResponse'] = _GETCONTEXTNAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetContextNameRequest = _reflection.GeneratedProtocolMessageType('GetContextNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCONTEXTNAMEREQUEST,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.get_context_name_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.GetContextNameRequest)
  })
_sym_db.RegisterMessage(GetContextNameRequest)

GetContextNameResponse = _reflection.GeneratedProtocolMessageType('GetContextNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCONTEXTNAMERESPONSE,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.get_context_name_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.GetContextNameResponse)
  })
_sym_db.RegisterMessage(GetContextNameResponse)


# @@protoc_insertion_point(module_scope)
