# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jio/brain/proto/knowledge/healthcare/req_res/get_attributes_of_symptom_and_disease.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jio.brain.proto.knowledge.healthcare.base import attribute_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_attribute__pb2
from jio.brain.proto.knowledge.healthcare.base import status_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jio/brain/proto/knowledge/healthcare/req_res/get_attributes_of_symptom_and_disease.proto',
  package='jio.brain.proto.knowledge.healthcare',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nXjio/brain/proto/knowledge/healthcare/req_res/get_attributes_of_symptom_and_disease.proto\x12$jio.brain.proto.knowledge.healthcare\x1a\x39jio/brain/proto/knowledge/healthcare/base/attribute.proto\x1a\x36jio/brain/proto/knowledge/healthcare/base/status.proto\"Q\n\'GetAttributesOfSymptomAndDiseaseRequest\x12\x12\n\nsymptom_id\x18\x01 \x01(\r\x12\x12\n\ndisease_id\x18\x02 \x03(\r\"\xb7\x01\n(GetAttributesOfSymptomAndDiseaseResponse\x12H\n\nattributes\x18\x01 \x03(\x0b\x32\x34.jio.brain.proto.knowledge.healthcare.base.Attribute\x12\x41\n\x06status\x18\x02 \x01(\x0b\x32\x31.jio.brain.proto.knowledge.healthcare.base.Statusb\x06proto3'
  ,
  dependencies=[jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_attribute__pb2.DESCRIPTOR,jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2.DESCRIPTOR,])




_GETATTRIBUTESOFSYMPTOMANDDISEASEREQUEST = _descriptor.Descriptor(
  name='GetAttributesOfSymptomAndDiseaseRequest',
  full_name='jio.brain.proto.knowledge.healthcare.GetAttributesOfSymptomAndDiseaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symptom_id', full_name='jio.brain.proto.knowledge.healthcare.GetAttributesOfSymptomAndDiseaseRequest.symptom_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='disease_id', full_name='jio.brain.proto.knowledge.healthcare.GetAttributesOfSymptomAndDiseaseRequest.disease_id', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=326,
)


_GETATTRIBUTESOFSYMPTOMANDDISEASERESPONSE = _descriptor.Descriptor(
  name='GetAttributesOfSymptomAndDiseaseResponse',
  full_name='jio.brain.proto.knowledge.healthcare.GetAttributesOfSymptomAndDiseaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='attributes', full_name='jio.brain.proto.knowledge.healthcare.GetAttributesOfSymptomAndDiseaseResponse.attributes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='jio.brain.proto.knowledge.healthcare.GetAttributesOfSymptomAndDiseaseResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=512,
)

_GETATTRIBUTESOFSYMPTOMANDDISEASERESPONSE.fields_by_name['attributes'].message_type = jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_attribute__pb2._ATTRIBUTE
_GETATTRIBUTESOFSYMPTOMANDDISEASERESPONSE.fields_by_name['status'].message_type = jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2._STATUS
DESCRIPTOR.message_types_by_name['GetAttributesOfSymptomAndDiseaseRequest'] = _GETATTRIBUTESOFSYMPTOMANDDISEASEREQUEST
DESCRIPTOR.message_types_by_name['GetAttributesOfSymptomAndDiseaseResponse'] = _GETATTRIBUTESOFSYMPTOMANDDISEASERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetAttributesOfSymptomAndDiseaseRequest = _reflection.GeneratedProtocolMessageType('GetAttributesOfSymptomAndDiseaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETATTRIBUTESOFSYMPTOMANDDISEASEREQUEST,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.get_attributes_of_symptom_and_disease_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.GetAttributesOfSymptomAndDiseaseRequest)
  })
_sym_db.RegisterMessage(GetAttributesOfSymptomAndDiseaseRequest)

GetAttributesOfSymptomAndDiseaseResponse = _reflection.GeneratedProtocolMessageType('GetAttributesOfSymptomAndDiseaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETATTRIBUTESOFSYMPTOMANDDISEASERESPONSE,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.get_attributes_of_symptom_and_disease_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.GetAttributesOfSymptomAndDiseaseResponse)
  })
_sym_db.RegisterMessage(GetAttributesOfSymptomAndDiseaseResponse)


# @@protoc_insertion_point(module_scope)
