# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jio/brain/proto/knowledge/healthcare/req_res/get_attribute_value.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jio.brain.proto.knowledge.healthcare.base import value_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_value__pb2
from jio.brain.proto.knowledge.healthcare.base import status_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jio/brain/proto/knowledge/healthcare/req_res/get_attribute_value.proto',
  package='jio.brain.proto.knowledge.healthcare',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nFjio/brain/proto/knowledge/healthcare/req_res/get_attribute_value.proto\x12$jio.brain.proto.knowledge.healthcare\x1a\x35jio/brain/proto/knowledge/healthcare/base/value.proto\x1a\x36jio/brain/proto/knowledge/healthcare/base/status.proto\"V\n\x18GetAttributeValueRequest\x12\x12\n\nsymptom_id\x18\x01 \x01(\r\x12\x14\n\x0c\x61ttribute_id\x18\x02 \x01(\r\x12\x10\n\x08value_id\x18\x03 \x01(\r\"\x9f\x01\n\x19GetAttributeValueResponse\x12?\n\x05value\x18\x01 \x01(\x0b\x32\x30.jio.brain.proto.knowledge.healthcare.base.Value\x12\x41\n\x06status\x18\x02 \x01(\x0b\x32\x31.jio.brain.proto.knowledge.healthcare.base.Statusb\x06proto3'
  ,
  dependencies=[jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_value__pb2.DESCRIPTOR,jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2.DESCRIPTOR,])




_GETATTRIBUTEVALUEREQUEST = _descriptor.Descriptor(
  name='GetAttributeValueRequest',
  full_name='jio.brain.proto.knowledge.healthcare.GetAttributeValueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symptom_id', full_name='jio.brain.proto.knowledge.healthcare.GetAttributeValueRequest.symptom_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attribute_id', full_name='jio.brain.proto.knowledge.healthcare.GetAttributeValueRequest.attribute_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_id', full_name='jio.brain.proto.knowledge.healthcare.GetAttributeValueRequest.value_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=309,
)


_GETATTRIBUTEVALUERESPONSE = _descriptor.Descriptor(
  name='GetAttributeValueResponse',
  full_name='jio.brain.proto.knowledge.healthcare.GetAttributeValueResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='jio.brain.proto.knowledge.healthcare.GetAttributeValueResponse.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='jio.brain.proto.knowledge.healthcare.GetAttributeValueResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=471,
)

_GETATTRIBUTEVALUERESPONSE.fields_by_name['value'].message_type = jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_value__pb2._VALUE
_GETATTRIBUTEVALUERESPONSE.fields_by_name['status'].message_type = jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2._STATUS
DESCRIPTOR.message_types_by_name['GetAttributeValueRequest'] = _GETATTRIBUTEVALUEREQUEST
DESCRIPTOR.message_types_by_name['GetAttributeValueResponse'] = _GETATTRIBUTEVALUERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetAttributeValueRequest = _reflection.GeneratedProtocolMessageType('GetAttributeValueRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETATTRIBUTEVALUEREQUEST,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.get_attribute_value_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.GetAttributeValueRequest)
  })
_sym_db.RegisterMessage(GetAttributeValueRequest)

GetAttributeValueResponse = _reflection.GeneratedProtocolMessageType('GetAttributeValueResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETATTRIBUTEVALUERESPONSE,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.get_attribute_value_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.GetAttributeValueResponse)
  })
_sym_db.RegisterMessage(GetAttributeValueResponse)


# @@protoc_insertion_point(module_scope)
