# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jio/brain/proto/knowledge/healthcare/req_res/get_disease_name.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jio.brain.proto.knowledge.healthcare.base import disease_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_disease__pb2
from jio.brain.proto.knowledge.healthcare.base import status_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jio/brain/proto/knowledge/healthcare/req_res/get_disease_name.proto',
  package='jio.brain.proto.knowledge.healthcare',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nCjio/brain/proto/knowledge/healthcare/req_res/get_disease_name.proto\x12$jio.brain.proto.knowledge.healthcare\x1a\x37jio/brain/proto/knowledge/healthcare/base/disease.proto\x1a\x36jio/brain/proto/knowledge/healthcare/base/status.proto\"+\n\x15GetDiseaseNameRequest\x12\x12\n\ndisease_id\x18\x01 \x01(\r\"q\n\x16GetDiseaseNameResponse\x12\x14\n\x0c\x64isease_name\x18\x01 \x01(\t\x12\x41\n\x06status\x18\x02 \x01(\x0b\x32\x31.jio.brain.proto.knowledge.healthcare.base.Statusb\x06proto3'
  ,
  dependencies=[jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_disease__pb2.DESCRIPTOR,jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2.DESCRIPTOR,])




_GETDISEASENAMEREQUEST = _descriptor.Descriptor(
  name='GetDiseaseNameRequest',
  full_name='jio.brain.proto.knowledge.healthcare.GetDiseaseNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='disease_id', full_name='jio.brain.proto.knowledge.healthcare.GetDiseaseNameRequest.disease_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=265,
)


_GETDISEASENAMERESPONSE = _descriptor.Descriptor(
  name='GetDiseaseNameResponse',
  full_name='jio.brain.proto.knowledge.healthcare.GetDiseaseNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='disease_name', full_name='jio.brain.proto.knowledge.healthcare.GetDiseaseNameResponse.disease_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='jio.brain.proto.knowledge.healthcare.GetDiseaseNameResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=380,
)

_GETDISEASENAMERESPONSE.fields_by_name['status'].message_type = jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2._STATUS
DESCRIPTOR.message_types_by_name['GetDiseaseNameRequest'] = _GETDISEASENAMEREQUEST
DESCRIPTOR.message_types_by_name['GetDiseaseNameResponse'] = _GETDISEASENAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetDiseaseNameRequest = _reflection.GeneratedProtocolMessageType('GetDiseaseNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDISEASENAMEREQUEST,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.get_disease_name_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.GetDiseaseNameRequest)
  })
_sym_db.RegisterMessage(GetDiseaseNameRequest)

GetDiseaseNameResponse = _reflection.GeneratedProtocolMessageType('GetDiseaseNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETDISEASENAMERESPONSE,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.get_disease_name_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.GetDiseaseNameResponse)
  })
_sym_db.RegisterMessage(GetDiseaseNameResponse)


# @@protoc_insertion_point(module_scope)
