# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jio/brain/proto/knowledge/healthcare/req_res/get_symptom.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jio.brain.proto.knowledge.healthcare.base import symptom_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_symptom__pb2
from jio.brain.proto.knowledge.healthcare.base import status_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jio/brain/proto/knowledge/healthcare/req_res/get_symptom.proto',
  package='jio.brain.proto.knowledge.healthcare',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n>jio/brain/proto/knowledge/healthcare/req_res/get_symptom.proto\x12$jio.brain.proto.knowledge.healthcare\x1a\x37jio/brain/proto/knowledge/healthcare/base/symptom.proto\x1a\x36jio/brain/proto/knowledge/healthcare/base/status.proto\"\'\n\x11GetSymptomRequest\x12\x12\n\nsymptom_id\x18\x01 \x01(\r\"\x9c\x01\n\x12GetSymptomResponse\x12\x43\n\x07symptom\x18\x01 \x01(\x0b\x32\x32.jio.brain.proto.knowledge.healthcare.base.Symptom\x12\x41\n\x06status\x18\x02 \x01(\x0b\x32\x31.jio.brain.proto.knowledge.healthcare.base.Statusb\x06proto3'
  ,
  dependencies=[jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_symptom__pb2.DESCRIPTOR,jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2.DESCRIPTOR,])




_GETSYMPTOMREQUEST = _descriptor.Descriptor(
  name='GetSymptomRequest',
  full_name='jio.brain.proto.knowledge.healthcare.GetSymptomRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symptom_id', full_name='jio.brain.proto.knowledge.healthcare.GetSymptomRequest.symptom_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=256,
)


_GETSYMPTOMRESPONSE = _descriptor.Descriptor(
  name='GetSymptomResponse',
  full_name='jio.brain.proto.knowledge.healthcare.GetSymptomResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symptom', full_name='jio.brain.proto.knowledge.healthcare.GetSymptomResponse.symptom', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='jio.brain.proto.knowledge.healthcare.GetSymptomResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=415,
)

_GETSYMPTOMRESPONSE.fields_by_name['symptom'].message_type = jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_symptom__pb2._SYMPTOM
_GETSYMPTOMRESPONSE.fields_by_name['status'].message_type = jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2._STATUS
DESCRIPTOR.message_types_by_name['GetSymptomRequest'] = _GETSYMPTOMREQUEST
DESCRIPTOR.message_types_by_name['GetSymptomResponse'] = _GETSYMPTOMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSymptomRequest = _reflection.GeneratedProtocolMessageType('GetSymptomRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSYMPTOMREQUEST,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.get_symptom_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.GetSymptomRequest)
  })
_sym_db.RegisterMessage(GetSymptomRequest)

GetSymptomResponse = _reflection.GeneratedProtocolMessageType('GetSymptomResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSYMPTOMRESPONSE,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.get_symptom_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.GetSymptomResponse)
  })
_sym_db.RegisterMessage(GetSymptomResponse)


# @@protoc_insertion_point(module_scope)
