# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jio/brain/proto/knowledge/healthcare/req_res/search_symptoms.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jio.brain.proto.knowledge.healthcare.base import search_response_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_search__response__pb2
from jio.brain.proto.knowledge.healthcare.base import status_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jio/brain/proto/knowledge/healthcare/req_res/search_symptoms.proto',
  package='jio.brain.proto.knowledge.healthcare',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nBjio/brain/proto/knowledge/healthcare/req_res/search_symptoms.proto\x12$jio.brain.proto.knowledge.healthcare\x1a?jio/brain/proto/knowledge/healthcare/base/search_response.proto\x1a\x36jio/brain/proto/knowledge/healthcare/base/status.proto\"E\n\x15SearchSymptomsRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x03(\r\x12\x0b\n\x03\x61ge\x18\x03 \x03(\r\"\xaf\x01\n\x16SearchSymptomsResponse\x12R\n\x0fsearch_response\x18\x01 \x03(\x0b\x32\x39.jio.brain.proto.knowledge.healthcare.base.SearchResponse\x12\x41\n\x06status\x18\x02 \x01(\x0b\x32\x31.jio.brain.proto.knowledge.healthcare.base.Statusb\x06proto3'
  ,
  dependencies=[jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_search__response__pb2.DESCRIPTOR,jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2.DESCRIPTOR,])




_SEARCHSYMPTOMSREQUEST = _descriptor.Descriptor(
  name='SearchSymptomsRequest',
  full_name='jio.brain.proto.knowledge.healthcare.SearchSymptomsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyword', full_name='jio.brain.proto.knowledge.healthcare.SearchSymptomsRequest.keyword', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='jio.brain.proto.knowledge.healthcare.SearchSymptomsRequest.gender', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='jio.brain.proto.knowledge.healthcare.SearchSymptomsRequest.age', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=298,
)


_SEARCHSYMPTOMSRESPONSE = _descriptor.Descriptor(
  name='SearchSymptomsResponse',
  full_name='jio.brain.proto.knowledge.healthcare.SearchSymptomsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='search_response', full_name='jio.brain.proto.knowledge.healthcare.SearchSymptomsResponse.search_response', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='jio.brain.proto.knowledge.healthcare.SearchSymptomsResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=476,
)

_SEARCHSYMPTOMSRESPONSE.fields_by_name['search_response'].message_type = jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_search__response__pb2._SEARCHRESPONSE
_SEARCHSYMPTOMSRESPONSE.fields_by_name['status'].message_type = jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_status__pb2._STATUS
DESCRIPTOR.message_types_by_name['SearchSymptomsRequest'] = _SEARCHSYMPTOMSREQUEST
DESCRIPTOR.message_types_by_name['SearchSymptomsResponse'] = _SEARCHSYMPTOMSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchSymptomsRequest = _reflection.GeneratedProtocolMessageType('SearchSymptomsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHSYMPTOMSREQUEST,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.search_symptoms_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.SearchSymptomsRequest)
  })
_sym_db.RegisterMessage(SearchSymptomsRequest)

SearchSymptomsResponse = _reflection.GeneratedProtocolMessageType('SearchSymptomsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHSYMPTOMSRESPONSE,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.req_res.search_symptoms_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.SearchSymptomsResponse)
  })
_sym_db.RegisterMessage(SearchSymptomsResponse)


# @@protoc_insertion_point(module_scope)
