server_add_entity:
	python -m api.add_entity.server

client_add_entity:
	python -m test.api.add_entity.client

server_metadata_lookup:
	python -m api.metadata_lookup.server

client_metadata_lookup:
	python -m test.api.metadata_lookup.client

server_add_collection_type:
	python -m api.add_collection_type.server

client_add_collection_type:
	python -m test.api.add_collection_type.client

server_get_entity:
	python -m api.get_entity.server

client_get_entity:
	python -m test.api.get_entity.client

server_add_attribute_type:
	python -m api.add_attribute_type.server

client_add_attribute_type:
	python -m test.api.add_attribute_type.client

server_add_bizid_to_entity:
	python -m api.add_bizid_to_entity.server

client_add_bizid_to_entity:
	python -m test.api.add_bizid_to_entity.client

server_delete_entity:
	python -m api.delete_entity.server

client_delete_entity:
	python -m test.api.delete_entity.client

server_delete_bizid:
	python -m api.delete_bizid.server

client_delete_bizid:
	python -m test.api.delete_bizid.client
	
server_add_predicate:
	python -m api.add_predicate.server

client_add_predicate:
	python -m test.api.add_predicate.client

server_add_entity_alias:
	python -m api.add_entity_alias.server

client_add_entity_alias:
	python -m test.api.add_entity_alias.client

server_delete_canonical_name:
	python -m api.delete_canonical_name.server

client_delete_canonical_name:
	python -m test.api.delete_canonical_name.client

server_get_predicate:
	python -m api.get_predicate.server

client_get_predicate:
	python -m test.api.get_predicate.client

server_get_attribute:
	python -m api.get_attribute.server

client_get_attribute:
	python -m test.api.get_attribute.client

server_get_attribute_id:
	python -m api.get_attribute_id.server

client_get_attribute_id:
	python -m test.api.get_attribute_id.client

server_get_attribute_value_id:
	python -m api.get_attribute_value_id.server

client_get_attribute_value_id:
	python -m test.api.get_attribute_value_id.client

server_get_entity_id_by_name:
	python -m api.get_entity_id_by_name.server

client_get_entity_id_by_name:
	python -m test.api.get_entity_id_by_name.client

server_get_entity_context:
	python -m api.get_entity_context.server

client_get_entity_context:
	python -m test.api.get_entity_context.client
	
server_has_entity:
	python -m api.has_entity.server

client_has_entity:
	python -m test.api.has_entity.client

server_has_biz_id:
	python -m api.has_biz_id.server

client_has_biz_id:
	python -m test.api.has_biz_id.client

server_graph_query:
	python -m api.graph_query.server

client_graph_query:
	python -m test.api.graph_query.client

server_has_canonical_name:
	python -m api.has_canonical_name.server

client_has_canonical_name:
	python -m test.api.has_canonical_name.client

server_delete_collection:
	python -m api.delete_collection.server

client_delete_collection:
	python -m test.api.delete_collection.client

server_get_canonical_name:
	python -m api.get_canonical_name.server

client_get_canonical_name:
	python -m test.api.get_canonical_name.client

server_get_alias:
	python -m api.get_alias.server

client_get_alias:
	python -m test.api.get_alias.client

server_get_all_biz_id_types_of_entity_id:
	python -m api.get_all_biz_id_types_of_entity_id.server

client_get_all_biz_id_types_of_entity_id:
	python -m test.api.get_all_biz_id_types_of_entity_id.client

server_get_entities_with_alias_name:
	python -m api.get_entities_with_alias_name.server

client_get_entities_with_alias_name:
	python -m test.api.get_entities_with_alias_name.client

server_add_attribute:
	python -m api.add_attribute.server

client_add_attribute:
	python -m test.api.add_attribute.client

server_get_entities_with_canonical_name:
	python -m api.get_entities_with_canonical_name.server

client_get_entities_with_canonical_name:
	python -m test.api.get_entities_with_canonical_name.client

server_delete_attribute:
	python -m api.delete_attribute.server

client_delete_attribute:
	python -m test.api.delete_attribute.client

server_delete_predicate:
	python -m api.delete_predicate.server

client_delete_predicate:
	python -m test.api.delete_predicate.client

server_add_canonical_name:
	python -m api.add_canonical_name.server

client_add_canonical_name:
	python -m test.api.add_canonical_name.client

server_delete_attribute_type:
	python -m api.delete_attribute_type.server

client_delete_attribute_type:
	python -m test.api.delete_attribute_type.client

server_enrich_api:
	python -m api.enrich_api.server

client_enrich_api:
	python -m test.api.enrich_api.client

test_pytest_has_entity:
	py.test -m has_entity

test_pytest_generate_report:
	pytest -vv --html=report.html
	
server_get_all_entity_ids_using_biz_id:
	python -m api.get_all_entity_ids_using_biz_id.server

client_get_all_entity_ids_using_biz_id:
	python -m test.api.get_all_entity_ids_using_biz_id.client

server_has_any_biz_id:
	python -m api.has_any_biz_id.server

client_has_any_biz_id:
	python -m test.api.has_any_biz_id.client

server_get_bizid_of_entityid:
	python -m api.get_bizid_of_entityid.server

client_get_bizid_of_entityid:
	python -m test.api.get_bizid_of_entityid.client

server_update_bizid_to_entity:
	python -m api.update_bizid_to_entity.server

client_update_bizid_to_entity:
	python -m test.api.update_bizid_to_entity.client

server_update_canonical_name:
	python -m api.update_canonical_name.server

client_update_canonical_name:
	python -m test.api.update_canonical_name.client

server_delete_entity_alias:
	python -m api.delete_entity_alias.server

client_delete_entity_alias:
	python -m test.api.delete_entity_alias.client

server_get_schema:
	python -m api.get_schema.server

client_get_schema:
	python -m test.api.get_schema.client

server_get_entities_instance:
	python -m api.get_entities_instance.server

client_get_entities_instance:
	python -m test.api.get_entities_instance.client

server_get_all_children:
	python -m api.get_all_children.server

client_get_all_children:
	python -m test.api.get_all_children.client

server_entity_id_lookup:
	python -m api.entity_id_lookup.server

client_entity_id_lookup:
	python -m test.api.entity_id_lookup.client

server_get_parent:
	python -m api.get_parent.server

client_get_parent:
	python -m test.api.get_parent.client

server_get_all_attributes:
	python -m api.get_all_attributes.server

client_get_all_attributes:
	python -m test.api.get_all_attributes.client

server_get_edge:
	python -m api.get_edge.server

client_get_edge:
	python -m test.api.get_edge.client

server_get_attribute_value:
	python -m api.get_attribute_value.server

client_get_attribute_value:
	python -m test.api.get_attribute_value.client

server_get_context:
	python -m api.get_context.server

client_get_context:
	python -m test.api.get_context.client

server_get_context_value_id:
	python -m api.get_context_value_id.server

client_get_context_value_id:
	python -m test.api.get_context_value_id.client

server_search_entity_by_context:
	python -m api.search_entity_by_context.server

client_search_entity_by_context:
	python -m test.api.search_entity_by_context.client

server_get_valid_entity_attribute_values_given_filter:
	python -m api.get_valid_entity_attribute_values_given_filter.server

client_get_valid_entity_attribute_values_given_filter:
	python -m test.api.get_valid_entity_attribute_values_given_filter.client

server_get_entity_name_by_id:
	python -m api.get_entity_name_by_id.server

client_get_entity_name_by_id:
	python -m test.api.get_entity_name_by_id.client

server_get_attribute_value_name:
	python -m api.get_attribute_value_name.server

client_get_attribute_value_name:
	python -m test.api.get_attribute_value_name.client

server_get_context_value_name:
	python -m api.get_context_value_name.server

client_get_context_value_name:
	python -m test.api.get_context_value_name.client