# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jio/brain/proto/knowledge/healthcare/base/symptom.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jio.brain.proto.knowledge.healthcare.base import attribute_pb2 as jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_attribute__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jio/brain/proto/knowledge/healthcare/base/symptom.proto',
  package='jio.brain.proto.knowledge.healthcare.base',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n7jio/brain/proto/knowledge/healthcare/base/symptom.proto\x12)jio.brain.proto.knowledge.healthcare.base\x1a\x39jio/brain/proto/knowledge/healthcare/base/attribute.proto\"\xa7\x01\n\x07Symptom\x12\n\n\x02id\x18\x01 \x01(\r\x12\x13\n\x0b\x65ntity_type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x04 \x01(\t\x12\r\n\x05query\x18\x05 \x01(\t\x12H\n\nattributes\x18\x06 \x03(\x0b\x32\x34.jio.brain.proto.knowledge.healthcare.base.Attributeb\x06proto3'
  ,
  dependencies=[jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_attribute__pb2.DESCRIPTOR,])




_SYMPTOM = _descriptor.Descriptor(
  name='Symptom',
  full_name='jio.brain.proto.knowledge.healthcare.base.Symptom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='jio.brain.proto.knowledge.healthcare.base.Symptom.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity_type', full_name='jio.brain.proto.knowledge.healthcare.base.Symptom.entity_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='jio.brain.proto.knowledge.healthcare.base.Symptom.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='jio.brain.proto.knowledge.healthcare.base.Symptom.display_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query', full_name='jio.brain.proto.knowledge.healthcare.base.Symptom.query', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='jio.brain.proto.knowledge.healthcare.base.Symptom.attributes', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=329,
)

_SYMPTOM.fields_by_name['attributes'].message_type = jio_dot_brain_dot_proto_dot_knowledge_dot_healthcare_dot_base_dot_attribute__pb2._ATTRIBUTE
DESCRIPTOR.message_types_by_name['Symptom'] = _SYMPTOM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Symptom = _reflection.GeneratedProtocolMessageType('Symptom', (_message.Message,), {
  'DESCRIPTOR' : _SYMPTOM,
  '__module__' : 'jio.brain.proto.knowledge.healthcare.base.symptom_pb2'
  # @@protoc_insertion_point(class_scope:jio.brain.proto.knowledge.healthcare.base.Symptom)
  })
_sym_db.RegisterMessage(Symptom)


# @@protoc_insertion_point(module_scope)
